services:
  cwm.sql:
    container_name: CWM.SQL
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - carworkshopmanagement2024

  cwm-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    hostname: cwm-rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672  
      - 8080:15672
      - 15692:15692
    expose:
      - 5672
      - 8080
    environment:
      - RABBITMQ_DEFAULT_USER=${RMQ_USER} 
      - RABBITMQ_DEFAULT_PASS=${RMQ_PASSWORD} 
    depends_on:
      - cwm.api
    networks:
      - carworkshopmanagement2024
    volumes:
      - ./docker_data/rabbitmq_data:/var/lib/rabbitmq
      - ./docker_data/rabbitmq_logs:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  cwm-smtp:
    restart: unless-stopped
    container_name: cwm-smtp
    hostname: cwm-smtp
    build: 
      context: .
      dockerfile: CWM.SMTP/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RabbitMQ:Host=cwm-rabbitmq
      - RabbitMQ:Port=${RMQ_PORT}
      - RabbitMQ:User=${RMQ_USER}
      - RabbitMQ:Password=${RMQ_PASSWORD}
      - RABBITMQ_PORT=5672
      - FromEmail=${FROM_EMAIL}
      - SmtpPass=${SMTP_PASS}
      - SmtpMail=${SMTP_USER}
    depends_on:
      cwm-rabbitmq:
        condition: service_healthy
    networks:
      - carworkshopmanagement2024

  cwm.api:
    container_name: CWM.API
    build:
      context: .
      dockerfile: CWM/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+
      - ConnectionStrings:DefaultConnection=Server=cwm.sql,1433;Database=${SQL_DATABASE};Trusted_Connection=False;Encrypt=False;User=${SQL_USER};Password=${SQL_PASSWORD};
      - RabbitMQ:Host=cwm-rabbitmq
      - RabbitMQ:Port=${RMQ_PORT}
      - RabbitMQ:User=${RMQ_USER}
      - RabbitMQ:Password=${RMQ_PASSWORD}
    ports:
      - ${API_PORT}:80
    depends_on:
      - cwm.sql
    networks:
      - carworkshopmanagement2024

networks:
  carworkshopmanagement2024:
   driver: bridge  