services:
  cwm.sql:
    container_name: CWM.SQL
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - carworkshopmanagement2024

  cwm.api:
    container_name: CWM.API
    build:
      context: .
      dockerfile: CWM/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=${API_HTTPS_PORT}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=SwPass#*****
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/2024-27-12.pfx
      - ConnectionStrings:DefaultConnection=Server=cwm.sql,1433;Database=${SQL_DATABASE};Trusted_Connection=False;Encrypt=False;User=${SQL_USER};Password=${SQL_PASSWORD};
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - ${API_PORT}:80
      - ${API_HTTPS_PORT}:443
    networks:
      - carworkshopmanagement2024

  cwm.rabbitmq:
    container_name: CWM.RabbitMQ
    image: rabbitmq:3.12.1-management
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RMQ_PASSWORD}
    ports:
      - ${RMQ_PORT}:5672
      - ${RMQ_ADMIN_PORT}:15672
    networks:
      - carworkshopmanagement2024

  cwm.smtp:
    container_name: CWM.SMTP
    build:
      context: .
      dockerfile: CWM.SMTP/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RabbitMQ:Host=hrms.rabbitmq
      - RabbitMQ:Port=${RMQ_PORT}
      - RabbitMQ:User=${RMQ_USER}
      - RabbitMQ:Password=${RMQ_PASSWORD}
      - MailSlurp:ApiKey=${MAILSLURP_API_KEY}
      - MailSlurp:InboxId=${MAILSLURP_INBOX_ID}
      - MailSlurp:SupportEmails=${MAILSLURP_SUPPORT_EMAILS}
    ports:
      - ${SMTP_PORT}:80
      - ${SMTP_HTTPS_PORT}:443
    depends_on:
      - cwm.rabbitmq
    networks:
      - carworkshopmanagement2024

networks:
  carworkshopmanagement2024:
   driver: bridge  